"""empty message

Revision ID: 726f329b2990
Revises: eb052c84168d
Create Date: 2022-03-02 09:02:58.558131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726f329b2990'
down_revision = 'eb052c84168d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'description')
    # ### end Alembic commands ###
